version: "3.9"

services:

  docs:
    build:
      context: docs/.
      dockerfile: Dockerfile
    env_file:
      - .env.prod-dev

  awt-tile-cache:
    image: registry.cevi.tools/cevi/awt_tile-caching:dev
    env_file:
      - .env.prod-dev

  awt-mapfish:
    image: registry.cevi.tools/cevi/awt_mapfish:dev
    env_file:
      - .env.prod-dev

  awt-swiss-tml:
    image: registry.cevi.tools/cevi/awt_swiss-tml-api:dev
    env_file:
      - .env.prod-dev

  awt-backend:
    build:
      context: python_program/.
      dockerfile: Dockerfile
    image: registry.cevi.tools/cevi/awt_backend:dev
    env_file:
      - .env.prod-dev

  awt-webinterface:
    build:
      context: .
      dockerfile: webinterface/Dockerfile
      # Used in the first stage of the Dockerfile, thus these env vars must be passed as args
      args:
        - ENVIRONMENT_FILE=.env.prod-dev
    image: registry.cevi.tools/cevi/awt_webinterface:dev
    env_file:
      - .env.prod-dev
