version: "3.9"

services:

  awt-tile-cache:
    image: registry.cevi.tools/cevi/awt_tile-caching:dev
    build: tile_caching
    env_file:
      - .env.dev

  awt-mapfish:
    image: registry.cevi.tools/cevi/awt_mapfish:dev
    build: pdf_map_export/.
    ports:
      - "8080:8080"
    depends_on:
      - awt-tile-cache
    env_file:
      - .env.dev

  awt-swiss-tml:
    image: registry.cevi.tools/cevi/awt_swiss-tml-api:dev
    build:
      context: swiss_TLM_api/.
    ports:
      - "1848:1848"
    volumes:
      - ./swiss_TLM_api/resources:/app/resources
      - ./swiss_TLM_api/index_cache:/app/index_cache
    env_file:
      - .env.dev

  awt-backend:
    image: registry.cevi.tools/cevi/awt_backend:dev
    build:
      context: python_program/.
    ports:
      - "5000:5000"
    depends_on:
      - awt-mapfish
      - awt-swiss-tml
    environment:
      TZ: Europe/Zurich
    env_file:
      - .env.dev

  awt-webinterface:
    image: registry.cevi.tools/cevi/awt_webinterface:dev
    build:
      context: .
      dockerfile: webinterface/Dockerfile
      args:
        # By default, we build in development mode. You can change the build mode by specifying $ANGULAR_CONFIGURATION.
        - configuration=${ANGULAR_CONFIGURATION:-development}
    ports:
      - "80:80"
    depends_on:
      - awt-backend
    env_file:
      - .env.dev