version: "3.9"

services:

  tile_cache:
    image: registry.test.cevi.tools/cevi/awtg_tile_caching:latest
    build: tile_caching

  mapfish:
    image: registry.test.cevi.tools/cevi/awtg_mapfish:latest
    build: pdf_map_export/.
    ports:
      - "8080:8080"
    depends_on:
      - tile_cache

  swiss_tml:
    image: registry.test.cevi.toolscevi/swiss_tml_api:latest
    build:
      context: swiss_TLM_api/.
    ports:
      - "1848:1848"
    volumes:
      - ./swiss_TLM_api/resources:/app/resources
      - ./swiss_TLM_api/index_cache:/app/index_cache

  backend:
    image: registry.test.cevi.tools/cevi/awtg_backend:latest
    build:
      context: python_program/.
    ports:
      - "5000:5000"
    depends_on:
      - mapfish
      - swiss_tml
    environment:
      TZ: Europe/Zurich

  webinterface:
    image: registry.test.cevi.tools/cevi/awtg_webinterface:latest
    build:
      context: .
      dockerfile: webinterface/Dockerfile
      args:
        # By default, we build in development mode. You can change the build mode by specifying $ANGULAR_CONFIGURATION.
        - configuration=${ANGULAR_CONFIGURATION:-development}
    ports:
      - "80:80"
    depends_on:
      - backend
