version: "3.9"

services:

  tile_cache:
    build: tile_caching

  mapfish:
    build: pdf_map_export/.
    ports:
      - "8080:8080"
    depends_on:
      - tile_cache
    healthcheck:
      test: "curl -f http://localhost:8080"
      interval: 2s
      timeout: 1s
      retries: 60

  swiss_tml:
    build:
      context: swiss_TLM_api/.
    ports:
      - "1848:1848"
    volumes:
      - ./swiss_TLM_api/resources:/app/resources
      - ./swiss_TLM_api/index_cache:/app/index_cache
    healthcheck:
      test: "curl -f http://localhost:1848/ready | grep 'ready'"
      interval: 2s
      timeout: 1s
      retries: 60

  backend:
    build:
      context: python_program/.
    ports:
      - "5000:5000"
    depends_on:
      swiss_tml:
        condition: service_healthy
      mapfish:
        condition: service_healthy
    environment:
      TZ: Europe/Zurich

  webinterface:
    build:
      context: webinterface/.
      args:
        # By default, we build in development mode. You can change the build mode by specifying $ANGULAR_CONFIGURATION.
        - configuration=${ANGULAR_CONFIGURATION:-development}
    ports:
      - "80:80"
    depends_on:
      - backend
