version: "3.9"

services:

  docs:
    build:
      context: docs/.
      dockerfile: dev-live.Dockerfile
    ports:
      - "4000:80"
    volumes:
      - ./docs:/app/src
      - /app/src/.vitepress/dist
      - /app/src/node_modules
    env_file:
      - .env.dev

  awt-tile-cache:
    build: tile_caching
    env_file:
      - .env.dev

  awt-mapfish:
    build: pdf_map_export/.
    ports:
      - "8080:8080"
    depends_on:
      - awt-tile-cache
    env_file:
      - .env.dev

  awt-swiss-tml:
    build:
      context: swiss_TLM_api/.
    ports:
      - "1848:1848"
    volumes:
      - ./swiss_TLM_api/resources:/app/resources
      - ./swiss_TLM_api/index_cache:/app/index_cache
    env_file:
      - .env.dev

  awt-backend:
    build:
      context: python_program/.
    ports:
      - "5000:5000"
    depends_on:
      - awt-mapfish
      - awt-swiss-tml
    environment:
      TZ: Europe/Zurich
    env_file:
      - .env.dev

  awt-webinterface:
    build:
      context: .
      dockerfile: webinterface/Dockerfile
      args:
        # By default, we build in development mode. You can change the build mode by specifying $ANGULAR_CONFIGURATION.
        - ANGULAR_BUILD_MODE=${ANGULAR_BUILD_MODE:-dev}
    ports:
      - "80:80"
    depends_on:
      - awt-backend
    env_file:
      - .env.dev