version: "3.9"

services:

  awt-route_engine:
    image: gisops/valhalla:latest
    container_name: valhalla_latest
    ports:
      - "8002:8002"
    volumes:
      - ./route_engine/sources/:/custom_files
    environment:
      # - tile_urls=https://download.geofabrik.de/europe/switzerland-latest.osm.pbf
      - server_threads=2  # determines how many threads will be used to run the valhalla server
      - use_tiles_ignore_pbf=True  # load existing valhalla_tiles.tar directly
      - build_elevation=False  # build elevation with "True" or "Force": will download only the elevation for areas covered by the graph tiles
      - build_admins=False  # build admins db with "True" or "Force"
      - build_time_zones=False  # build timezone db with "True" or "Force"
      - build_tar=True  # build an indexed tar file from the tile_dir for faster graph loading times
      - force_rebuild=False  # forces a rebuild of the routing tiles with "True"

  awt-tile-cache:
    image: registry.cevi.tools/cevi/awt_tile-caching:latest
    build: tile_caching

  awt-mapfish:
    image: registry.cevi.tools/cevi/awt_mapfish:latest
    build: pdf_map_export/.
    ports:
      - "8080:8080"
    depends_on:
      - awt-tile-cache

  awt-swiss-tml:
    image: registry.cevi.tools/cevi/awt_swiss-tml-api:latest
    build:
      context: swiss_TLM_api/.
    ports:
      - "1848:1848"
    volumes:
      - ./swiss_TLM_api/resources:/app/resources
      - ./swiss_TLM_api/index_cache:/app/index_cache

  awt-backend:
    image: registry.cevi.tools/cevi/awt_backend:latest
    build:
      context: python_program/.
    ports:
      - "5000:5000"
    depends_on:
      - awt-mapfish
      - awt-swiss-tml
    environment:
      TZ: Europe/Zurich

  awt-webinterface:
    image: registry.cevi.tools/cevi/awt_webinterface:latest
    build:
      context: .
      dockerfile: webinterface/Dockerfile
      args:
        # By default, we build in development mode. You can change the build mode by specifying $ANGULAR_CONFIGURATION.
        - configuration=${ANGULAR_CONFIGURATION:-development}
    ports:
      - "80:80"
    depends_on:
      - awt-backend
      - awt-route_engine
