name: DevBuild

on:
  push:
    branches:
      - 'master'

env:
  ANGULAR_CONFIGURATION: dev_build

jobs:
  prodBuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: registry.cevi.tools
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the stack
        run: docker-compose --env-file .env.prod build

      - name: Push containers to registry
        run: docker-compose push
