name: Testing
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Built the stack
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml up -d
    env:
      - ANGULAR_CONFIGURATION: cypress